# -*- coding: utf-8 -*-
"""m1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/amandapdb/ab31c85e3f6d1e466900daf2d28a1e17/m1.ipynb

# Projeto: PrevixTor

### 1. Identificação do Grupo
* **Instituição:** Faculdade Engenheiro Salvador Arena
* **Curso:** [Engenharia de Controle e Automação]
* **Grupo:** [04]
* **Integrantes:**
    * [Amanda Perini] - RA: [062210013]
    * [Arthur Delgado] - RA: [062210036]
    * [Beatriz Ashiley] - RA: [062210037]
    * [Henrique Lopes] - RA: [062210001]

---

### 2. Área Problema Selecionada
O grupo seleciona uma das áreas norteadoras abaixo para o desenvolvimento do projeto:
* [X] Manutenção Preditiva de Zero-Downtime
* [ ] Eficiência Energética e Descarbonização via Smart Grids
* [ ] Controle de Qualidade Autônomo com Visão Computacional
* [ ] Gêmeos Digitais (Digital Twins) e Analytics em Tempo Real


---

### 3. Diagnóstico e Definição do Problema
Esta seção apresenta a fundamentação do desafio. O grupo descreve o cenário de atuação e justifica a importância da solução proposta.
* **Contexto:** O projeto aborda o cenário da Indústria 4.0, com foco em motores elétricos utilizados em esteiras industriais, onde a operação contínua é essencial para a produtividade.
* **Problema:** A dificuldade central reside na ocorrência de falhas inesperadas em motores elétricos, que causam paradas não planejadas e não são previstas com precisão por métodos tradicionais,
                impactando diretamete na produtividade do setor em questão.
* **Impacto:** A solução visa otimizar paradas não planejadas, diminuir custos de manutenção e aumentar a confiabilidade operacional por meio da previsão de falhas baseada em dados.

---

### 4. Arquitetura de Dados (Fonte e Dataset)
O projeto utiliza dados estruturados para alimentar os modelos preditivos.
* **Origem dos Dados:** [(https://archive.ics.uci.edu/ml/datasets/AI4I+2020+Predictive+Maintenance+Dataset)].
* **Características:** O conjunto de dados apresenta variáveis como:
-Sensores Industriais
-Temperatura do Ar
-Temperatura do Processo
-Velocidade de Rotação (RPM)
-Torque
-Desgaste da Ferramenta
-Tipo de Produto
-Indicadores de Falha
* **Volume:** O dataset conta com 10.000 registros e 14 atributos técnicos.

---

### 5. Plano de Tratamento de Dados (ETL)
O pipeline de dados segue as seguintes etapas de processamento:
1. **Extração:** A ingestão ocorre via arquivos CSV do dataset AI4I, obtidos do repositório UCI.
2. **Transformação:** O grupo aplica a limpeza de valores ausentes, a remoção de outliers e a normalização das escalas numéricas.
                      São realizadas etapas de limpeza dos dados, incluindo verificação de valores nulos, remoção de outliers e padronização das variáveis numéricas.
                      Também é feita a codificação de variáveis categóricas (como o tipo de produto) e seleção de atributos relevantes para a modelagem.
3. **Carga:** Os dados tratados são disponibilizados na pasta `/data/processed` para consumo dos modelos de Machine Learning.

---

##**Análise Exploratótia de Dados (EDA)
#Dataset: Manutenção Preditiva de Motores Industriais
O objetivo dessa análise é exploraros dados, identificar padrões, correlações e possíveis outliers que possam impactar a previsão de falhas em motores industriais.

**Primeiramente vamos extrair os dados:**
"""

from google.colab import files
files.upload()

import pandas as pd
import numpy as np
df = pd.read_csv('/content/ai4i2020.csv')
df.head()

"""**Vamos analisar todos os dados de coluna:**"""

df.info()

"""**É possível perceber que a coluna Non-Null Count significa que temos 10.000 dados não nulos, ou seja, 100%, mas vamos confirmar mais para frente. Primeiro vamos ver um resumo estatístico das colunas**"""

df.describe()

"""**E confirmar se realmente não possui valores nulos nessa tabela:**"""

df.isnull().sum()

"""**Realmente não possui nenhum valor nulo.**


**Agora vamos remover colunas desnecessárias:**

No caso escolhemos a UDI pois é basicamente o número da linha e o Product ID que é o código do produto que podemos usar o Type com a mesma finalidade, ficando assim menos redundante.
"""

df = df.drop(['UDI', 'Product ID'], axis=1)

df.head()

"""**Agora vamos remover dados duplicados.**"""

df = df.drop_duplicates()

df.duplicated().sum()

"""**Isso significa que não temos dados duplicados. Não identificamos nenhum tipo de inconsistência**"""

df.describe()

"""**Agora vamos tratar Outliers em variáveis que possuem números:**"""

cols_numericas = df.select_dtypes(include=['int64', 'float64']).columns

Q1 = df[cols_numericas].quantile(0.25)
Q3 = df[cols_numericas].quantile(0.75)
IQR = Q3 - Q1

df = df[~((df[cols_numericas] < (Q1 - 1.5 * IQR)) |
          (df[cols_numericas] > (Q3 + 1.5 * IQR))).any(axis=1)]

df.shape

"""**Agora, ao invés de 10.000 dados, temos 9.256, o restante foi considerado Outlier pelo modelo. Já o 12 é porque tinhamos 14 colunas e limpamos 2 por considerá-las desnecessárias**

**O modelo de Machine Learning não entende texto portanto vamos trocar a varíavel Type por números 0 e 1:**
"""

df = pd.get_dummies(df, columns=['Type'])

df.head()

"""**Agora vamos Normalizar os dados:**"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

cols_numericas = [
    'Air temperature [K]',
    'Process temperature [K]',
    'Rotational speed [rpm]',
    'Torque [Nm]',
    'Tool wear [min]'
]

df[cols_numericas] = scaler.fit_transform(df[cols_numericas])

df.head()

df.describe()

"""**Agora faremos uma matriz de correlação para tirarmos alguns insights.**"""

df.corr()

"""Foi identificada uma forte correlação positiva (0.87) entre a temperatura do ar e a temperatura do processo, indicando que ambas variáveis estão diretamente relacionadas.

Além disso, observou-se uma forte correlação negativa (-0.89) entre a velocidade rotacional e o torque, sugerindo que o aumento da velocidade está associado à redução do torque.


##Gráfico 1 - Heatmap de Correlação
"""

import seaborn as sns
import matplotlib.pyplot as plt

colunas_corr = [
    'Air temperature [K]',
    'Process temperature [K]',
    'Rotational speed [rpm]',
    'Torque [Nm]',
    'Tool wear [min]'
]

corr = df[colunas_corr].corr()
corr

plt.figure(figsize=(10,8))
sns.heatmap(corr, annot=True, fmt=".2f")
plt.title("Matriz de Correlação (Ajustada)")
plt.show()

"""## Análise de Correlação

A matriz de correlação revelou relações importantes entre as variáveis do sistema.

Foi identificada uma forte correlação positiva (0.88) entre a temperatura do ar e a temperatura do processo, indicando que ambas estão diretamente relacionadas.

Além disso, observou-se uma forte correlação negativa (-0.89) entre a velocidade rotacional e o torque, sugerindo que o aumento da velocidade está associado à redução do torque.

As demais variáveis apresentaram correlação próxima de zero, indicando baixa influência linear entre elas.


## Gráfico 2 - Boxplot (Diagrama de Caixa)
"""

colunas = [
    'Air temperature [K]',
    'Process temperature [K]',
    'Rotational speed [rpm]',
    'Torque [Nm]',
    'Tool wear [min]'
]

plt.figure(figsize=(10,6))
sns.boxplot(data=df[colunas])

plt.xticks(rotation=45)
plt.title("Outliers nas Variáveis Principais")

plt.show()

"""## Análise de Outliers

A partir do boxplot das variáveis principais, foi possível identificar a presença de outliers em algumas variáveis do sistema.

Observa-se que as variáveis de velocidade rotacional e torque apresentam maior quantidade de valores extremos, indicando possíveis variações anormais no comportamento do equipamento.

As variáveis de temperatura apresentam distribuição mais estável, com menor incidência de outliers.

A identificação desses valores é importante, pois outliers podem impactar diretamente a performance de modelos de Machine Learning, sendo necessária sua análise e tratamento na etapa de ETL.


##Gráfico 3 - Histograma (Distribuição de Dados)
"""

df[['Air temperature [K]', 'Torque [Nm]']].hist(figsize=(10,5))
plt.show()

"""## Análise de Distribuição dos Dados

Os histogramas das variáveis temperatura do ar e torque demonstram que os dados apresentam uma distribuição relativamente equilibrada.

A variável temperatura apresenta comportamento próximo de uma distribuição normal, indicando estabilidade no sistema.

Já o torque apresenta uma leve dispersão maior, o que pode indicar variações no esforço aplicado durante o funcionamento do equipamento.

A análise da distribuição é importante para entender o comportamento dos dados e garantir a adequação dos modelos de Machine Learning.

## Validação de Hipóteses

Com base na análise exploratória dos dados, foram levantadas e validadas as seguintes hipóteses:

- Existe uma relação direta entre a temperatura do ar e a temperatura do processo, evidenciada pela forte correlação positiva observada.
- O aumento da velocidade rotacional está associado à redução do torque, conforme demonstrado pela correlação negativa significativa.
- A presença de outliers em variáveis como torque e velocidade indica possíveis variações anormais no comportamento do equipamento.

As hipóteses foram validadas por meio da análise estatística e visualização dos dados.
"""

df.to_csv('processed_data.csv', index=False)

from google.colab import files
files.download('processed_data.csv')

"""## Conclusão

A análise exploratória dos dados permitiu identificar padrões relevantes no comportamento do sistema, destacando relações importantes entre variáveis críticas.

A identificação de correlações e outliers contribui diretamente para a compreensão do problema e será fundamental para o desenvolvimento de modelos de Machine Learning mais eficientes nas próximas etapas.

O processo de ETL garantiu a qualidade dos dados, tornando a análise mais confiável.

---

### 6. Estrutura do Repositório
A organização das pastas facilita a manutenção e o versionamento do projeto:
* `/docs`: Contém os diagramas de fluxo de dados e a documentação técnica.
* `/data/raw`: Armazena os arquivos de dados originais (não modificados).
* `/data/processed`: Armazena os dados após a execução do script de ETL.
* `/scripts`: Contém os códigos Python responsáveis pelo tratamento dos dados.
* `requirements.txt`: Lista todas as bibliotecas necessárias para a execução do projeto.

---

### 7. Instruções para Execução

Para reproduzir o projeto:

1. Fazer o download do dataset a partir do repositório UCI.

2. Acessar o notebook no Google Colab.

3. Realizar o upload do arquivo CSV no ambiente do Colab.

4. Executar as células sequencialmente para realizar o tratamento dos dados e geração do arquivo processado.
"""